
datasource:
  url: jdbc:mysql://localhost:3306/microservices
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  hibernate:
    ddl-auto: update
  show-sql: true

application:
  name: USER-SERVICE

central_log:
  client_service: client_service UPDATE NOWasdasdasd
  api_service: api_service
  account_service: account_service
  fund_service: fund_service
  user_service: user_service

account_db:
  url: localhost:33062
  username: root
  password: password
  ddl-auto: create-drop


client_db:
  url: localhost:3308
  username: root
  password: password
  ddl-auto: create-drop


api_db:
  url: localhost:3307
  username: root
  password: password
  ddl-auto: create-drop


fund_db:
  url: localhost:3309
  username: root
  password: password
  ddl-auto: create-drop

user_db:
  url: localhost:3310
  username: root
  password: password
  ddl-auto: create-drop
